print('¿qué sale de la cruza entre un mono y un pato?')
input()
print('¡un monopatín!')
print()
print('¿Porqué vuelan los pájaros pa\'l sur?')
input()
print('¡Porque caminando tardarían muchísimo!')
print()
print('¿En qué se parecen una familia, un bombero y un barco?')
input()
print("No sé... ¿en qué se parecen?")
input()
print('En que el bombero y el barco tienen casco.')
input()
print('¿Y la familia?', end='')
print(' -Bien, gracias.')
input()
print('¿Cuál es el último animal que subió al arca de Noé?')
input()
print('El del-fin.')
input()
print('¿Cómo se dice pañuelo en japonés?')
input()
print('Saka-moko.')
input()
print('¿Cómo se dice disparo en árabe?')
input()
print('Ahí-va-la-bala.')
input()
print('¿Qué le dice un gusano a otro gusano? ')
input()
print('Voy a dar una vuelta a la manzana.')
input()
print('Un gato empieza a ladrar en el tejado de una casa. Otro gato, sorprendido, le dice: Estás loco gato, ¿por qué ladras en vez de maullar?')
input()
print('El gatito le responde: ¿A caso no puedo aprender otro idioma?')
input()
print('Sale el doctor después de un parto y el padre de la criatura le pregunta: ¿Doctor cómo salió todo? El doctor le dice: todo salió bien, pero tuvimos que colocarle oxígeno al bebé.')
input()
print('El padre, horrorizado, le dice: pero doctor, nosotros queríamos ponerle Gabriel.')
input()
print('Un pez le pregunta a otro pez: ¿qué hace tu mamá? ')
input()
print('Este le contesta: Nada, ¿y la tuya qué hace?')
input()
print('¿Cuál es el colmo de Aladdín? ')
input()
print('Tener mal genio.')
input()
print('Si se muere una pulga, ¿a dónde va? ')
input()
print('Al pulgatorio.')
input()
print('¿Por qué las focas miran siempre hacia arriba? ')
input()
print('¡Porque ahí están los focos!')
input()
